### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by danielhollas** [PHOTOX/promdens#35]
Which one? MIT is the most straightforward.

**Comment by danielhollas** [comment]
> To set the 'promdens' description, author, links, classifiers, and other details for your next release, use the [project metadata fields in your pyproject.toml file](https://packaging.python.org/tutorials/packaging-projects/#creating-pyproject-toml). Updating these fields will not change the metadata for past releases. Additionally, you must use [Twine](https://twine.readthedocs.io/) to upload your files in order to get full support for these fields. See [the Python Packaging User Guide](https://packaging.python.org/guides/section-build-and-publish/) for more help.

**Comment by JanosJiri** [comment]
Honeslty, I have never dealt with licenses before so I know nothing. I check with google and I found also GNU General Public License and BSD license. They all seem similar, I don't have any preference. If you have any experience, I'm happy to go with your suggestion.
